apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: customer-app
  template:
    metadata:
      labels:
        app: customer-app
    spec:
      containers:
        - name: customer-app
          image: myregistry.azurecr.io/customer-app:v1
          ports:
            - containerPort: 3001
---

apiVersion: v1
kind: Service
metadata:
  name: customer-app
spec:
  type: ClusterIP
  selector:
    app: customer-app
  ports:
  - name: http
    port: 3001
    targetPort: 3001
