apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-app
  template:
    metadata:
      labels:
        app: customer-app
    spec:
      containers:
        - name: customer-app
          image: acrca.azurecr.io/frontend-image:v1
          ports:
            - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: custom-app-service
spec:
  selector:
    app: custom-app
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: LoadBalancer
